openapi: 3.0.3
info:
  title: 'Laravel API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
tags:
  -
    name: Endpoints
    description: ''
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/auth/login:
    post:
      summary: 'Login user with email or phone'
      operationId: loginUserWithEmailOrPhone
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/auth/register:
    post:
      summary: ''
      operationId: postApiAuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: b
                lastname:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: 'n'
                  nullable: true
                avatar:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                  nullable: true
                sex:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: g
                  nullable: true
                address:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: z
                  nullable: true
                phone:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: m
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: gulgowski.asia@example.com
                  nullable: true
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: 'vYgxwmi/#'
                city:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: m
                  nullable: true
                country:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: 'y'
                  nullable: true
                role:
                  type: string
                  description: ''
                  example: acheteur
                  enum:
                    - acheteur
                    - vendeur
                  nullable: true
                id_card_recto:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                id_card_verso:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
              required:
                - firstname
                - phone
                - password
                - id_card_recto
                - id_card_verso
      security: []
  /api/auth/logout:
    post:
      summary: ''
      operationId: postApiAuthLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/wallet/balance:
    get:
      summary: "Get the current balance of the authenticated user's wallet."
      operationId: getTheCurrentBalanceOfTheAuthenticatedUsersWallet
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/transactions/transfer:
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  description: 'Must be at least 1.'
                  example: 16
                recipient_identifier:
                  type: string
                  description: ''
                  example: architecto
                offline_id:
                  type: string
                  description: ''
                  example: architecto
                  nullable: true
              required:
                - amount
                - recipient_identifier
      security: []
  /api/transactions/history:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/transactions/{transaction_id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: transaction_id
        description: 'The ID of the transaction.'
        example: 1
        required: true
        schema:
          type: integer
  /api/transaction-types:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/transaction-statuses:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/user/profile:
    get:
      summary: "Get the authenticated user's profile with wallet."
      operationId: getTheAuthenticatedUsersProfileWithWallet
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/user/update:
    post:
      summary: "Update the authenticated user's profile."
      operationId: updateTheAuthenticatedUsersProfile
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: b
                  nullable: true
                lastname:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: 'n'
                  nullable: true
                sex:
                  type: string
                  description: 'Must not be greater than 10 characters.'
                  example: gzmiyv
                  nullable: true
                address:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: d
                  nullable: true
                city:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: l
                  nullable: true
                country:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: j
                  nullable: true
                avatar:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                  nullable: true
      security: []
  /api/user/search:
    get:
      summary: 'Search for a user by phone or account number (for transfers).'
      operationId: searchForAUserByPhoneOrAccountNumberforTransfers
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: 'Must be at least 3 characters.'
                  example: bngzmiyvdljnikhwaykcmyuwpwlvqwrsitcpscqldzsnrwtujwvlxjklqppwqbewtnnoqitpxn
              required:
                - query
      security: []
