openapi: 3.0.3
info:
  title: 'Laravel API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
tags:
  -
    name: Endpoints
    description: ''
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/auth/login:
    post:
      summary: 'Login user with email or phone'
      operationId: loginUserWithEmailOrPhone
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/auth/register:
    post:
      summary: ''
      operationId: postApiAuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: b
                lastname:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: 'n'
                  nullable: true
                avatar:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                  nullable: true
                sex:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: g
                  nullable: true
                address:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: z
                  nullable: true
                phone:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: m
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: gulgowski.asia@example.com
                  nullable: true
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: 'vYgxwmi/#'
                city:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: m
                  nullable: true
                country:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: 'y'
                  nullable: true
                role:
                  type: string
                  description: ''
                  example: vendeur
                  enum:
                    - acheteur
                    - vendeur
                  nullable: true
                id_card_recto:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
                id_card_verso:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 2048 kilobytes.'
              required:
                - firstname
                - phone
                - password
                - id_card_recto
                - id_card_verso
      security: []
  /api/auth/logout:
    post:
      summary: ''
      operationId: postApiAuthLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/wallet/balance:
    get:
      summary: "Get the current balance of the authenticated user's wallet."
      operationId: getTheCurrentBalanceOfTheAuthenticatedUsersWallet
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/transactions/transfer:
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  description: 'Must be at least 1.'
                  example: 16
                wallet_uuid:
                  type: string
                  description: 'Must be a valid UUID. The <code>uuid</code> of an existing record in the wallets table.'
                  example: a4855dc5-0acb-33c3-b921-f4291f719ca0
                offline_id:
                  type: string
                  description: ''
                  example: architecto
                  nullable: true
              required:
                - amount
                - wallet_uuid
      security: []
  /api/transactions/history:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/transaction-types:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/transaction-statuses:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
